In [1]:
import pandas as pd

In [3]:
# Define the file path
file_path = r'C:\Users\Lenovo\OneDrive-CornellUniversity\Desktop\Cornell Meng CS\MEng Project 2\extracted_data.csv'

# Read the CSV file
data = pd.read_csv(file_path)

# List of universities to count
universities = [
    'University of Pennsylvania',
    'Columbia University',
    'Cornell University',
    'Yale University',
    'Harvard University'
]

# Calculate the count for each university
counts = data['Institution'].value_counts()

# Print the counts for the specified universities
for university in universities:
    print(f"{university}: {counts.get(university, 0)}")

University of Pennsylvania: 12640
Columbia University: 10310
Cornell University: 52450
Yale University: 3593
Harvard University: 9672

In [11]:
import spacy

In [14]:
# Load the spaCy model
nlp = spacy.load("en_core_web_sm")

In [17]:
# Function to clean text using spaCy
def clean_text(text):
    if isinstance(text, float) and pd.isna(text):
        return 'EmptyString'
    doc = nlp(text)
    clean_tokens = [token.lemma_.lower() for token in doc if not token.is_stop and not token.is_punct and not token.like_num and token.is_alpha]
    cleaned_text = " ".join(clean_tokens)
    return cleaned_text

In [18]:
# Add the "CleanedDescription" column
data['CleanedDescription'] = data['Description'].apply(clean_text)

In [20]:
data.head(20)

,Institution,Field,Year,Description,TotalNoOfWords,CleanedDescription
0,Harvard University,Mathematics,2014,This course is an introduction to groups and r...,53,course introduction group ring foundational co...
1,Cornell University,Basic Skills,2014,Lecture/laboratory course designed to introduc...,152,lecture laboratory course design introduce yea...
2,Cornell University,Biology,2020,This two-semester sequence investigates the fu...,86,semester sequence investigate fundamental livi...
3,Cornell University,Basic Skills,2022,NaN,0,EmptyString
4,Cornell University,Political Science,2018,Entertainment forms of political communication...,106,entertainment form political communication pop...
5,Yale University,Mathematics,2008,Introduction to the theory of computational co...,41,introduction theory computational complexity b...
6,Cornell University,Music,2020,"Punk Cultureâ€“comprised of music, fashion, lite...",118,punk culture comprise music fashion literature...
7,Cornell University,Library Science,1990,NaN,0,EmptyString
8,Harvard University,Economics,2012,The globalization of financial markets gives c...,227,globalization financial market give country op...
9,Harvard University,Philosophy,2016,Few metaphysicians would identify as Cartesian...,203,metaphysician identify cartesian dualist today...
10,Yale University,Political Science,2013,NaN,0,EmptyString
11,Cornell University,Chinese,2016,This course is designed for those who have stu...,105,course design study mandarin advanced level eq...
12,Cornell University,Religion,2019,Jerusalem is a holy city to the adherents of t...,192,jerusalem holy city adherent great monotheisti...
13,Harvard University,English Literature,2016,NaN,0,EmptyString
14,Cornell University,Natural Resource Management,2018,This course is designed to explore environment...,190,course design explore environmental conflict r...
15,Cornell University,Philosophy,2021,An introductory survey of ancient Greek philos...,32,introductory survey ancient greek philosophy c...
16,Cornell University,Political Science,2021,This course explores how a rapidly changing me...,87,course explore rapidly change media environmen...
17,Cornell University,Mathematics,2020,Matrices and linear systems can be data-sparse...,56,matrix linear system data sparse wide variety ...
18,University of Pennsylvania,English Literature,2012,NaN,0,EmptyString
19,Cornell University,Theatre Arts,2017,NaN,0,EmptyString

In [28]:
import pandas as pd

# Function to count words in a string
def count_words(description):
    if pd.isna(description):
        return 0
    return len(description.split())

# Add the "total number of words" column
data['TotalNoOfWords'] = data['Description'].apply(count_words)
data['CountofCleanedWords'] = data['CleanedDescription'].apply(count_words)

# Save the updated DataFrame to a new CSV file
output_file_path = r'C:\Users\Lenovo\OneDrive-CornellUniversity\Desktop\Cornell Meng CS\MEng Project 2\updated_extracted_data.csv'
data.to_csv(output_file_path, index=False)

print(f"Updated CSV saved to {output_file_path}")

Updated CSV saved to C:\Users\Lenovo\OneDrive-CornellUniversity\Desktop\Cornell Meng CS\MEng Project 2\updated_extracted_data.csv

In [22]:
data.head()

,Institution,Field,Year,Description,TotalNoOfWords,CleanedDescription,CountofCleanedWords
0,Harvard University,Mathematics,2014,This course is an introduction to groups and r...,53,course introduction group ring foundational co...,26
1,Cornell University,Basic Skills,2014,Lecture/laboratory course designed to introduc...,152,lecture laboratory course design introduce yea...,95
2,Cornell University,Biology,2020,This two-semester sequence investigates the fu...,86,semester sequence investigate fundamental livi...,50
3,Cornell University,Basic Skills,2022,NaN,0,EmptyString,1
4,Cornell University,Political Science,2018,Entertainment forms of political communication...,106,entertainment form political communication pop...,56

In [26]:
# Print the "Description" and "CleanedDescription" columns of the 4th and 5th rows
print("2th row Description:\n", data.loc[2, 'Description'])
print("2th row CleanedDescription:\n", data.loc[2, 'CleanedDescription'])
print()
print("4th row Description:\n", data.loc[4, 'Description'])
print("4th row CleanedDescription:\n", data.loc[4, 'CleanedDescription'])

2th row Description:
 This two-semester sequence investigates the fundamentals of living systems. Through lectures
and laboratory investigations we will explore the structure and function of the cell, the biological
macromolecules that build it up and investigate the biological systems. In the second semester,
the students review the following topics: Genetics, Evolution and Plant & Animal Form &
Function. Students become familiar with methods of taxonomy and phylogenetic analysis and
engage fundamental principles of evolution including mechanisms of genetic variation and
inheritance, population dynamics, extinction and the origin of species.
2th row CleanedDescription:
 semester sequence investigate fundamental living system lecture laboratory investigation explore structure function cell biological macromolecule build investigate biological system semester student review follow topic genetic evolution plant animal form function student familiar method taxonomy phylogenetic analysis engage fundamental principle evolution include mechanism genetic variation inheritance population dynamic extinction origin specie

4th row Description:
 Entertainment forms of political communication such as popular music are very often neglected in research of political communication, although popular music has a long and varied association with politics. It has provided the soundtrack to political protest and been the object of political censorship; politicians have courted pop stars and pop stars â€” like Bono of U2 â€” have acted as politicians. This class will therefore examine the various interaction between popular music and politics, and how popular music can contribute to our understanding of political thought and action, but also critically reflect upon the effects of popular music on people's political perceptions, attitudes and behavior.
4th row CleanedDescription:
 entertainment form political communication popular music neglect research political communication popular music long varied association politic provide soundtrack political protest object political censorship politician court pop star pop star like bono act politician class examine interaction popular music politic popular music contribute understanding political thought action critically reflect effect popular music people political perception attitude behavior

In [27]:
import pandas as pd

# Define the file path of the updated CSV
updated_file_path = r'C:\Users\Lenovo\OneDrive-CornellUniversity\Desktop\Cornell Meng CS\MEng Project 2\updated_extracted_data.csv'

# Read the updated CSV file
data = pd.read_csv(updated_file_path)

# Find the rows with the least and most number of words
least_words_row = data.loc[data['TotalNoOfWords'].idxmin()]
most_words_row = data.loc[data['TotalNoOfWords'].idxmax()]

# Print the rows
print("Row with the least number of words:")
print(least_words_row)
print("\nRow with the most number of words:")
print(most_words_row)

Row with the least number of words:
Institution            Cornell University
Field                        Basic Skills
Year                                 2022
Description                           NaN
TotalNoOfWords                          0
CleanedDescription            EmptyString
CountofCleanedWords                     1
Name: 3, dtype: object

Row with the most number of words:
Institution                                              Yale University
Field                                                 English Literature
Year                                                                2003
Description            Reading and writing are skills practiced and d...
TotalNoOfWords                                                      6271
CleanedDescription     reading writing skill practice develop life sk...
CountofCleanedWords                                                 3205
Name: 80382, dtype: object

In [30]:
data.head()

,Institution,Field,Year,Description,TotalNoOfWords,CleanedDescription,CountofCleanedWords
0,Harvard University,Mathematics,2014,This course is an introduction to groups and r...,53,course introduction group ring foundational co...,26
1,Cornell University,Basic Skills,2014,Lecture/laboratory course designed to introduc...,152,lecture laboratory course design introduce yea...,95
2,Cornell University,Biology,2020,This two-semester sequence investigates the fu...,86,semester sequence investigate fundamental livi...,50
3,Cornell University,Basic Skills,2022,NaN,0,EmptyString,1
4,Cornell University,Political Science,2018,Entertainment forms of political communication...,106,entertainment form political communication pop...,56

In [31]:
import pandas as pd
from keybert import KeyBERT
from sentence_transformers import SentenceTransformer
from transformers import BertModel, BertTokenizer
import torch
from scipy.spatial.distance import cosine

# Initialize KeyBERT with a specific SentenceTransformer model
sentence_model = SentenceTransformer('all-MiniLM-L6-v2')
kw_model = KeyBERT(model=sentence_model)

# Define candidate business-related keywords
candidate_keywords = [
    "marketing", "finance", "investment", "startup",
    "entrepreneurship", "management", "corporate", "economics",
    "venture capital", "market analysis", "business development",
    "commercialization", "innovation", "strategic planning"
]

# Initialize BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Function to get word embedding using BERT with caching
embedding_cache = {}

def get_word_embedding(word, tokenizer, model):
    if word in embedding_cache:
        return embedding_cache[word]
    inputs = tokenizer(word, return_tensors='pt')
    with torch.no_grad():
        outputs = model(**inputs)
    embedding = outputs.last_hidden_state.mean(dim=1).squeeze()
    embedding_cache[word] = embedding
    return embedding

# Precompute embeddings for candidate keywords
candidate_embeddings = [get_word_embedding(word, tokenizer, model) for word in candidate_keywords]

# Function to calculate cosine similarity
def cosine_similarity(vec1, vec2):
    return 1 - cosine(vec1, vec2)

# Function to count business-related keywords in text using KeyBERT
def count_business_keywords(text):
    if pd.isna(text):
        return 0
    keywords = kw_model.extract_keywords(text, keyphrase_ngram_range=(1, 2), stop_words='english', top_n=50, diversity=0.4)
    count = 0
    for keyword, _ in keywords:
        keyword_vec = get_word_embedding(keyword, tokenizer, model)
        for business_word_vec in candidate_embeddings:
            similarity = cosine_similarity(keyword_vec, business_word_vec)
            if similarity >= 0.85:
                count += 1
                break  # Assuming each keyword is counted only once even if it matches multiple business keywords
    return count

# Define the file path of the updated CSV
updated_file_path = r'C:\Users\Lenovo\OneDrive-CornellUniversity\Desktop\Cornell Meng CS\MEng Project 2\updated_extracted_data.csv'

# Read the updated CSV file
data = pd.read_csv(updated_file_path)


# Create a test DataFrame by selecting specific rows
test_data = data.iloc[3:10000].copy()

# Add the "BusinessWords" column to the test DataFrame
test_data['BusinessWords'] = test_data['CleanedDescription'].apply(count_business_keywords)

# Print the test DataFrame
print(test_data[['Description', 'CleanedDescription', 'BusinessWords']])

                                         Description  \
3                                                NaN
4  Entertainment forms of political communication...
5  Introduction to the theory of computational co...
6  Punk Cultureâ€“comprised of music, fashion, lite...

                                  CleanedDescription  BusinessWords
3                                        EmptyString              0
4  entertainment form political communication pop...              7
5  introduction theory computational complexity b...             12
6  punk culture comprise music fashion literature...              8